apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qa-reader-clusterrole
rules:
  # Read-only access to application resources
  - apiGroups: ["", "apps", "batch"]
    resources:
      - pods
      - pods/log
      - deployments
      - replicasets
      - services
      - configmaps
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  # Read events for troubleshooting
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
